AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: String
    Description: SLIIT_Test

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #ImageId: ami-041feb57c611358bd 
      ImageId:  ami-053b0d53c279acc90
      InstanceType: t3.small
      KeyName: SLIIT_Test
      SecurityGroupIds:
        - sg-074acc700bc27ee1a 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          #install docker
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker ubuntu
          #install git
          sudo apt update
          sudo apt install git
          sudo git clone https://github.com/manuja/DeveloperIQ.git
          #install curl
          sudo apt install curl
          #install minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          #install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          minikube start
          #sudo kubectl create --filename /DeveloperIQ/examdocapp/deployment.yaml
          #sudo kubectl create --filename /DeveloperIQ/examdocapp/service.yaml
          #sudo minikube image load developeriq:latest

Outputs:
  EC2PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp

