AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: String
    Description: SLIIT_Test

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-041feb57c611358bd 
      InstanceType: t3.small
      KeyName: SLIIT_Test
      SecurityGroupIds:
        - sg-074acc700bc27ee1a 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -aG docker ec2-user
          sudo apt-get install git-all
          sudo git clone https://github.com/manuja/DeveloperIQ.git
          sudo apt install curl
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          # (Install kubectl and other dependencies as needed)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          minikube start --driver=kvm2

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceIdentifier: aecs
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: Bd#19891104
      DBInstanceClass: db.t3.micro
      AutoMinorVersionUpgrade: false  # Disable automatic minor version upgrades
      BackupRetentionPeriod: 0        # Set backup retention period to 0 days (disabling automatic backups)
      CopyTagsToSnapshot: false
      VPCSecurityGroups:
        - sg-074acc700bc27ee1a  # Replace with your security group ID
      PubliclyAccessible: true
      

Outputs:
  EC2PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
  RDSHostName:
    Description: Hostname of the RDS instance
    Value: !GetAtt MyRDSInstance.Endpoint.Address

